[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "codeyz"
version = "0.1.0"
dependencies = [
    "openai",
    "python-dotenv",
    "typer",
    "rich",
    "fastapi",
    "uvicorn",
    "pytest",
    "httpx",
    "ruff",
]

[project.scripts]
codeyz = "packages.cli.main:app"

[tool.setuptools.packages.find]
where = ["."]
include = ["packages*"]
